// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL || "postgresql://postgres.fbnghxdleykoqrdqdpjw:QNEn8Y6%40jbdFEn%3F@aws-1-eu-central-1.pooler.supabase.com:6543/postgres?sslmode=require",
  },
});
